CREATE TABLE incidents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    location VARCHAR(255) NOT NULL,
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    crime_type VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    source_link VARCHAR(2083) NOT NULL,
    verified TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE evidence (
    id INT AUTO_INCREMENT PRIMARY KEY,
    incident_id INT NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    media_link VARCHAR(2083) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE CASCADE
);
